"""empty message

Revision ID: 62a6b0e918ff
Revises: 391d89a2198f
Create Date: 2020-07-24 01:05:28.214389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a6b0e918ff'
down_revision = '391d89a2198f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'groups', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_column('groups', 'email')
    # ### end Alembic commands ###
